name: Quality Checks

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version to use (e.g. 20.x)
        required: true
        type: string
      upload-artifact:
        description: Whether to upload the built dist as an artifact
        required: false
        default: false
        type: boolean

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload build artifact (dist)
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error



